name= 'glseq'
version= '2.0'
packages= ['glseq', 'glseq.condor_glseq']
url= 'https://github.com/MichaelLampe/glseq2'
license= 'GNU General Public License Version 3'
author= 'Michael Lampe'
author_email= 'MichaelTheLampe@Gmail.com'
description= 'GLBRC Customizable RNASeq Pipeline Platform'
download_url = 'https://github.com/MichaelLampe/GlSeq2/tarball/2.0'
keywords = ["GLBRC","rna", "rna_seq", "rna seq", "rna seq pipeline", "pipeline"]
install_requires = ["networkx","matplotlib"]